### ISSUE TITLE
如何在路由里引入验证中间件

### ISSUE THREAD

**Issue by baryon** [nswbmw/N-club#13]
比如N-Club的的路由
`http://localhost:3000/topic/57d65f08c0d001f037b165da
`

如何让只有已经登陆的用户查看这个主题，未登录的用户，跳转到登录页面，登录以后，再自动跳转回来

**Comment by nswbmw** [comment]
1. 在 routes/topic/*.id.js 的 get 方法中验证 this.session 是否为  null
2. 如果是未登录，则跳转的 /signin?redirect={当前页面的encode后的url}，signin路由从query获取redirct，登陆成功后跳转到这个redirect地址
