### ISSUE TITLE
co-cache这个模块用到了redis

### ISSUE THREAD

**Issue by zeroone001** [nswbmw/N-club#5]
请问，两种不同的数据库可以一起用吗？？

**Comment by nswbmw** [comment]
你是说两个不同的redis吗，可以啊。你也可以把已有的redis连接传到co-cache

**Comment by zeroone001** [comment]
首先感谢分享的项目，我是说这个项目中用到了mongoDB ,还用到了redis,这两个可以一起使用是吧，我看到co-cache这个模块用到了ioredis这个模块，也就是说需要同时开启mongoDB和redis,才能运行这个项目是吗？能不能只mongoDB

**Comment by nswbmw** [comment]
需要同时开启mongoDB和redis的

**Comment by zeroone001** [comment]
谢谢～～
